# delete http://localhost:8000/api/remove/a07b3812-0222-4502-8d33-816737999eaf
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImpvZUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTYwMTMwMjc4OSwiZXhwIjoxNjAxMzAzMDg5fQ.eYYjO6goCSrBUPPJGuEgdP52fmuVfPz4XluVv3mRwUM



# get http://localhost:8000/api/bookbyid/47973684-9a08-4921-983f-998468124356

# get http://localhost:8000/api/getbooks


# get http://localhost:8000/api/getpublishers
get http://localhost:8000/api/publisher/and


# post http://localhost:8000/api/login



# post http://localhost:8000/api/add
# Content-Type: application/json
# {
#     "PRICE": 9,
#     "WRITTEN_BY": "Fog Doyle",
#     "PUBLISHED_BY": "Andromediy",
#     "TITLE": "Tihuana67"
# }